Reading All CSV's

In [ ]:
import pandas as pd

sales = pd.read_csv("Sales.csv", encoding='latin1')
customers = pd.read_csv("Customers.csv", encoding='latin1')
products = pd.read_csv("Products.csv", encoding='latin1')
stores = pd.read_csv("Stores.csv", encoding='latin1')
exchange = pd.read_csv("Exchange_Rates.csv", encoding='latin1')

Initial Inspection Sales.csv

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB

In [ ]:
sales.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

In [ ]:
sales.shape

(62884, 9)

In [ ]:
sales.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
62879    False
62880    False
62881    False
62882    False
62883    False
Length: 62884, dtype: bool

In [ ]:
missing_percentage = sales.isnull().sum() / len(sales) *100
print ("Null values % per column : \n", missing_percentage[missing_percentage > 0])
print("\n Total NAN count: ",sales.isnull().sum().sum())

Null values % per column :
 Delivery Date    79.064627
dtype: float64

 Total NAN count:  49719

Data Cleaning sales.csv

In [ ]:
sales['Order Date'] = pd.to_datetime(sales['Order Date'])

sales['Delivery Date'] = pd.to_datetime(
    sales['Delivery Date'], errors='coerce')

sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  datetime64[ns]
 3   Delivery Date  13165 non-null  datetime64[ns]
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: datetime64[ns](2), int64(6), object(1)
memory usage: 4.3+ MB

Inital Inspection products.csv

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB

In [ ]:
products.head()

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [ ]:
products.shape

(2517, 10)

In [ ]:
products.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2512    False
2513    False
2514    False
2515    False
2516    False
Length: 2517, dtype: bool

In [ ]:
missing_percentage = products.isnull().sum() / len(products) *100
print ("Null values % per column : \n", missing_percentage[missing_percentage > 0])
print("\n Total NAN count: ",products.isnull().sum().sum())

Null values % per column :
 Series([], dtype: float64)

 Total NAN count:  0

Data Cleaning products.csv

In [ ]:
products['Unit Price USD'] = (
    products['Unit Price USD']
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float))

products['Unit Cost USD'] = (
    products['Unit Cost USD']
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float))

products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   float64
 5   Unit Price USD  2517 non-null   float64
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 196.8+ KB

Inital Inspection customers.csv

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB

In [ ]:
customers.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [ ]:
customers.shape

(15266, 10)

In [ ]:
missing_percentage = customers.isnull().sum() / len(customers) *100
print ("Null values % per column : \n", missing_percentage[missing_percentage > 0])
print("\n Total NAN count: ",customers.isnull().sum().sum())

Null values % per column :
 State Code    0.065505
dtype: float64

 Total NAN count:  10

Data Cleaning customers.csv

In [ ]:
customers['Birthday'] = pd.to_datetime(customers['Birthday'])

customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 1.2+ MB

In [23]:
customers['State Code'].fillna('NA', inplace = True)

/tmp/ipython-input-2991224844.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers['State Code'].fillna('NA', inplace = True)

Inital Inspection stores.csv

In [24]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.7+ KB

In [25]:
stores.head()

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

In [27]:
stores.shape

(67, 5)

In [28]:
missing_percentage = stores.isnull().sum() / len(stores) *100
print ("Null values % per column : \n", missing_percentage[missing_percentage > 0])
print("\n Total NAN count: ",stores.isnull().sum().sum())

Null values % per column :
 Square Meters    1.492537
dtype: float64

 Total NAN count:  1

Data Cleaning stores.csv

In [29]:
stores['Square Meters'].fillna(stores['Square Meters'].median(), inplace=True)

/tmp/ipython-input-3572564898.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  stores['Square Meters'].fillna(stores['Square Meters'].median(), inplace=True)

In [30]:
stores['Open Date'] = pd.to_datetime(stores['Open Date'])

stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  67 non-null     float64
 4   Open Date      67 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 2.7+ KB

EDA
1. Merging all tables

In [31]:
# merging sales with products in master_df
master_df=sales.merge(products, on='ProductKey', how='left')

master_df.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,Contoso,White,31.27,68.00,406,Cameras & Camcorders Accessories,4,Cameras and camcorders
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,A. Datum,Silver,141.47,427.00,402,Digital SLR Cameras,4,Cameras and camcorders
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,Fabrikam,Black,220.64,665.94,803,Microwaves,8,Home Appliances
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD,Contoso SLR Camera M146 Orange,Contoso,Orange,148.08,322.00,402,Digital SLR Cameras,4,Cameras and camcorders
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD,Adventure Works Laptop8.9 E0890 White,Adventure Works,White,166.20,326.00,301,Laptops,3,Computers

In [32]:
# merging customers in master_df
master_df = master_df.merge(customers,
    on='CustomerKey',
    how='left')

master_df.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,Product Name,...,Category,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,...,Cameras and camcorders,Male,Tyler Vaught,London,ON,Ontario,N5W 5K6,Canada,North America,1971-03-23
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,...,Cameras and camcorders,Male,Frank Upchurch,Auberry,CA,California,93602,United States,North America,1995-11-20
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,...,Home Appliances,Male,Frank Upchurch,Auberry,CA,California,93602,United States,North America,1995-11-20
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD,Contoso SLR Camera M146 Orange,...,Cameras and camcorders,Female,Joan Roche,Red Deer,AB,Alberta,T4N 2A6,Canada,North America,1962-08-24
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD,Adventure Works Laptop8.9 E0890 White,...,Computers,Female,Joan Roche,Red Deer,AB,Alberta,T4N 2A6,Canada,North America,1962-08-24

In [33]:
# merging stores in master_df
master_df = master_df.merge(stores,
    on='StoreKey',
    how='left')

master_df.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,Product Name,...,State Code,State_x,Zip Code,Country_x,Continent,Birthday,Country_y,State_y,Square Meters,Open Date
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,...,ON,Ontario,N5W 5K6,Canada,North America,1971-03-23,Canada,Nunavut,1210.0,2015-04-04
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,...,CA,California,93602,United States,North America,1995-11-20,Online,Online,1347.5,2010-01-01
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,...,CA,California,93602,United States,North America,1995-11-20,Online,Online,1347.5,2010-01-01
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD,Contoso SLR Camera M146 Orange,...,AB,Alberta,T4N 2A6,Canada,North America,1962-08-24,Online,Online,1347.5,2010-01-01
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD,Adventure Works Laptop8.9 E0890 White,...,AB,Alberta,T4N 2A6,Canada,North America,1962-08-24,Online,Online,1347.5,2010-01-01

Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.

In [34]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 31 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order Number    62884 non-null  int64
 1   Line Item       62884 non-null  int64
 2   Order Date      62884 non-null  datetime64[ns]
 3   Delivery Date   13165 non-null  datetime64[ns]
 4   CustomerKey     62884 non-null  int64
 5   StoreKey        62884 non-null  int64
 6   ProductKey      62884 non-null  int64
 7   Quantity        62884 non-null  int64
 8   Currency Code   62884 non-null  object
 9   Product Name    62884 non-null  object
 10  Brand           62884 non-null  object
 11  Color           62884 non-null  object
 12  Unit Cost USD   62884 non-null  float64
 13  Unit Price USD  62884 non-null  float64
 14  SubcategoryKey  62884 non-null  int64
 15  Subcategory     62884 non-null  object
 16  CategoryKey     62884 non-null  int64
 17  Category        62884 non-null  object
 18  Gender          62884 non-null  object
 19  Name            62884 non-null  object
 20  City            62884 non-null  object
 21  State Code      62884 non-null  object
 22  State_x         62884 non-null  object
 23  Zip Code        62884 non-null  object
 24  Country_x       62884 non-null  object
 25  Continent       62884 non-null  object
 26  Birthday        62884 non-null  datetime64[ns]
 27  Country_y       62884 non-null  object
 28  State_y         62884 non-null  object
 29  Square Meters   62884 non-null  float64
 30  Open Date       62884 non-null  datetime64[ns]
dtypes: datetime64[ns](4), float64(3), int64(8), object(16)
memory usage: 14.9+ MB

2. Calculating revenue

In [35]:
master_df['Revenue USD'] = (
    master_df['Quantity'] * master_df['Unit Price USD'])

master_df['Profit USD'] = ((master_df['Unit Price USD'] -
     master_df['Unit Cost USD']) *
    master_df['Quantity'])

master_df[['Revenue USD', 'Profit USD']].describe()

        Revenue USD    Profit USD
count  62884.000000  62884.000000
mean     886.640156    519.411748
std     1648.480286   1052.204029
min        0.950000      0.470000
25%      115.000000     61.560000
50%      360.000000    194.440000
75%      969.000000    540.140000
max    31999.900000  21397.700000

3. Total revenue

In [37]:
print("Total Revenue:", master_df['Revenue USD'].sum())

Total Revenue: 55755479.589999996

4. Total profit

In [38]:
print (" Total Profit:", master_df['Profit USD'].sum())

 Total Profit: 32662688.380000003

5. Profit margin

In [40]:
print ("Profit margin:",(master_df['Profit USD'].sum() / master_df['Revenue USD'].sum()) * 100)

Profit margin: 58.58202390184122

6. Top 10 Products by Revenue

In [41]:
print("Top 10 Products by Revenue:",
      master_df.groupby('Product Name')['Revenue USD']
      .sum().sort_values(ascending=False).head(10))

Top 10 Products by Revenue: Product Name
WWI Desktop PC2.33 X2330 Black                 505450.00
Adventure Works Desktop PC2.33 XD233 Silver    466089.00
Adventure Works Desktop PC2.33 XD233 Brown     464151.00
Adventure Works Desktop PC2.33 XD233 Black     447678.00
Adventure Works Desktop PC2.33 XD233 White     437019.00
WWI Desktop PC2.33 X2330 White                 424578.00
WWI Desktop PC2.33 X2330 Brown                 422740.00
Adventure Works 52" LCD HDTV X590 White        394398.64
Adventure Works 52" LCD HDTV X590 Black        374098.71
WWI Desktop PC2.33 X2330 Silver                360248.00
Name: Revenue USD, dtype: float64

7. Revenue by Country

In [45]:
print("Revenue by Country:",
      master_df.groupby('Country_x')['Revenue USD']
      .sum().sort_values(ascending=False).head(10))

Revenue by Country: Country_x
United States     29871631.17
United Kingdom     7084088.12
Germany            5414149.80
Canada             4724334.63
Australia          2708137.61
Italy              2475645.77
Netherlands        1962154.27
France             1515338.22
Name: Revenue USD, dtype: float64

8. customer age analysis

In [46]:
from datetime import datetime

today = datetime.today()
master_df['Age'] = (today - master_df['Birthday']).dt.days // 365

master_df.groupby(pd.cut(master_df['Age'], bins=[18,25,35,45,60,80]))['Revenue USD'].sum()

/tmp/ipython-input-2603252424.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  master_df.groupby(pd.cut(master_df['Age'], bins=[18,25,35,45,60,80]))['Revenue USD'].sum()

Age
(18, 25]     1846690.79
(25, 35]     8500771.67
(35, 45]     8227592.76
(45, 60]    12429469.84
(60, 80]    16442336.13
Name: Revenue USD, dtype: float64

**RFM Analysis (Customer Segmentation)**

1. Create Snapshot Date

In [47]:
# We need a reference date (latest order date)
snapshot_date = master_df['Order Date'].max() + pd.Timedelta(days=1)

snapshot_date

Timestamp('2021-02-21 00:00:00')

2. Build RFM Table

In [58]:
rfm = master_df.groupby('CustomerKey').agg({
    'Order Date': lambda x: (snapshot_date - x.max()).days,  # Recency
    'Order Number': 'count',                                # Frequency
    'Revenue USD': 'sum'                                    # Monetary
})

rfm.rename(columns={
    'Order Date': 'Recency',
    'Order Number': 'Frequency',
    'Revenue USD': 'Monetary'
}, inplace=True)

rfm.head()

             Recency  Frequency  Monetary
CustomerKey
301              468          1    592.00
325              414         10   5787.67
554              444          4    951.71
1042            1083          3   1124.91
1314            1160          5   2539.86

3. Create RFM Scores (1–5 Scale)

In [60]:
rfm['R_score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4,3,2,1])
rfm['F_score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])
rfm['M_score'] = pd.qcut(rfm['Monetary'], 5, labels=[1,2,3,4,5])

print(rfm['R_score'].head(5))
print(rfm['F_score'].head(5))
print(rfm['M_score'].head(5))

CustomerKey
301     3
325     4
554     3
1042    1
1314    1
Name: R_score, dtype: category
Categories (5, int64): [5 < 4 < 3 < 2 < 1]
CustomerKey
301     1
325     5
554     3
1042    2
1314    3
Name: F_score, dtype: category
Categories (5, int64): [1 < 2 < 3 < 4 < 5]
CustomerKey
301     1
325     4
554     2
1042    2
1314    3
Name: M_score, dtype: category
Categories (5, int64): [1 < 2 < 3 < 4 < 5]

In [65]:
# Combine Scores
rfm['RFM_Score'] = rfm['R_score'].astype(str) + \
                   rfm['F_score'].astype(str) + \
                   rfm['M_score'].astype(str)

print(rfm['RFM_Score'].head(5))

CustomerKey
301     311
325     454
554     332
1042    122
1314    133
Name: RFM_Score, dtype: object

4. Customer Segmentation

In [69]:
def segment_customer(row):
    if row['RFM_Score'] == '555':
        return 'Champions'
    elif row['R_score'] >= 4 and row['F_score'] >= 4:
        return 'Loyal Customers'
    elif row['R_score'] >= 4:
        return 'Recent Customers'
    elif row['F_score'] >= 4:
        return 'Frequent Customers'
    elif row['M_score'] >= 4:
        return 'Big Spenders'
    else:
        return 'At Risk'

rfm['Segment'] = rfm.apply(segment_customer, axis=1)

print(rfm['Segment'].head(10))

CustomerKey
301              At Risk
325      Loyal Customers
554              At Risk
1042             At Risk
1314             At Risk
1568     Loyal Customers
1585        Big Spenders
1626    Recent Customers
1642             At Risk
1863     Loyal Customers
Name: Segment, dtype: object

5. Segment Distribution

In [70]:
print(rfm['Segment'].value_counts())

Segment
At Risk               4162
Recent Customers      2152
Frequent Customers    2133
Loyal Customers       2091
Big Spenders           818
Champions              531
Name: count, dtype: int64

6. Revenue by Segment

In [72]:
rfm.merge(master_df[['CustomerKey','Revenue USD']], on='CustomerKey') \
   .groupby('Segment')['Revenue USD'].sum() \
   .sort_values(ascending=False)

Segment
Frequent Customers    15889204.49
Loyal Customers       14912826.97
Champions              7519838.03
Big Spenders           6130786.39
At Risk                5664753.47
Recent Customers       5638070.24
Name: Revenue USD, dtype: float64

**Product Analysis**

1. Top Selling Products

In [73]:
top_products = master_df.groupby('Product Name').agg({
    'Revenue USD': 'sum',
    'Quantity': 'sum'
}).sort_values(by='Revenue USD', ascending=False).head(10)

top_products

                                             Revenue USD  Quantity
Product Name
WWI Desktop PC2.33 X2330 Black                 505450.00       550
Adventure Works Desktop PC2.33 XD233 Silver    466089.00       481
Adventure Works Desktop PC2.33 XD233 Brown     464151.00       479
Adventure Works Desktop PC2.33 XD233 Black     447678.00       462
Adventure Works Desktop PC2.33 XD233 White     437019.00       451
WWI Desktop PC2.33 X2330 White                 424578.00       462
WWI Desktop PC2.33 X2330 Brown                 422740.00       460
Adventure Works 52" LCD HDTV X590 White        394398.64       136
Adventure Works 52" LCD HDTV X590 Black        374098.71       129
WWI Desktop PC2.33 X2330 Silver                360248.00       392

2. Category Performance

In [81]:
category_perf = master_df.groupby('Category').agg({
    'Revenue USD': 'sum',
    'Profit USD': 'sum'
}).sort_values(by='Revenue USD', ascending=False)

# Profit Margin
category_perf['Profit Margin %'] = (category_perf['Profit USD'] /
                                    category_perf['Revenue USD']) * 100
category_perf

                               Revenue USD   Profit USD  Profit Margin %
Category
Computers                      19301595.46  11277447.90        58.427543
Home Appliances                10795478.59   6296338.85        58.323851
Cameras and camcorders          6520168.02   3919800.99        60.118098
Cell phones                     6183791.22   3498626.54        56.577372
TV and Video                    5928982.69   3536694.39        59.650948
Audio                           3169627.74   1827851.77        57.667711
Music, Movies and Audio Books   3131006.44   1909259.17        60.979088
Games and Toys                   724829.43    396668.77        54.725809

3. Loss-Making Products

In [84]:
loss_products = master_df[master_df['Profit USD'] < 1]

loss_products.groupby('Product Name')['Profit USD'].sum().sort_values().head(10)

Product Name
SV USB Sync Charge Cable E700 Black     0.98
SV USB Data Cable E600 Silver           1.41
SV USB Sync Charge Cable E700 Silver    1.96
SV USB Sync Charge Cable E700 White     1.96
SV USB Data Cable E600 Grey             2.35
SV USB Data Cable E600 Black            2.82
SV USB Data Cable E600 Pink             2.82
SV USB Sync Charge Cable E700 Blue      4.90
Name: Profit USD, dtype: float64

4. Brand Analysis

In [86]:
brand_perf = master_df.groupby('Brand').agg({
    'Revenue USD': 'sum',
    'Profit USD': 'sum'
}).sort_values(by='Revenue USD', ascending=False)

brand_perf

                      Revenue USD  Profit USD
Brand
Adventure Works       11849909.32  6937318.88
Contoso               10792325.32  6321209.14
Wide World Importers   9172800.41  5367028.30
Fabrikam               6807893.52  4061475.11
The Phone Company      5386820.00  3057762.90
Proseware              3212628.02  1935287.10
Litware                2659498.78  1553765.19
Southridge Video       2578595.93  1522876.84
A. Datum               1486207.80   883502.31
Northwind Traders      1126069.54   649413.31
Tailspin Toys           682730.95   373049.30

**STORE ANALYSIS**

1. Store Performance

In [89]:
store_perf = master_df.groupby('StoreKey').agg({
    'Revenue USD': 'sum',
    'Profit USD': 'sum',
    'Order Number': 'count'
}).sort_values(by='Revenue USD', ascending=False)

store_perf.head(10)

          Revenue USD  Profit USD  Order Number
StoreKey
0         11404324.63  6672692.64         13165
55         1417885.41   830551.75          1518
50         1394738.06   819659.12          1519
54         1384396.24   810300.06          1498
9          1336150.06   774757.55          1577
57         1325611.89   784095.76          1442
45         1318787.92   761271.82          1471
61         1305684.43   764997.20          1485
59         1302272.44   754702.32          1472
64         1259350.98   745283.99          1353

In [90]:
# Merging store info with store performance
store_analysis = store_perf.merge(stores, on='StoreKey', how='left')
store_analysis.head()

,StoreKey,Revenue USD,Profit USD,Order Number,Country,State,Square Meters,Open Date
0,0,11404324.63,6672692.64,13165,Online,Online,1347.5,2010-01-01
1,55,1417885.41,830551.75,1518,United States,Nevada,2000.0,2009-12-15
2,50,1394738.06,819659.12,1519,United States,Kansas,2000.0,2008-03-06
3,54,1384396.24,810300.06,1498,United States,Nebraska,2000.0,2013-06-07
4,9,1336150.06,774757.55,1577,Canada,Northwest Territories,1500.0,2005-03-04

2. Store Size vs Revenue

In [91]:
# Does bigger store = more revenue?

store_analysis[['Square Meters', 'Revenue USD']].corr()

               Square Meters  Revenue USD
Square Meters       1.000000     0.163258
Revenue USD         0.163258     1.000000